In [1]:
import numpy as np

def create_array():
    print("\nArray Creation:")
    print("1. 1D Array")
    print("2. 2D Array")
    print("3. 3D Array")
    choice = int(input("Enter your choice: "))

    if choice == 1:
        n = int(input("Enter number of elements: "))
        elements = list(map(int, input("Enter elements separated by space: ").split()))
        return np.array(elements)

    elif choice == 2:
        r = int(input("Enter number of rows: "))
        c = int(input("Enter number of columns: "))
        elements = list(map(int, input(f"Enter {r*c} elements separated by space: ").split()))
        return np.array(elements).reshape(r, c)

    elif choice == 3:
        x = int(input("Enter dimension 1: "))
        y = int(input("Enter dimension 2: "))
        z = int(input("Enter dimension 3: "))
        elements = list(map(int, input(f"Enter {x*y*z} elements separated by space: ").split()))
        return np.array(elements).reshape(x, y, z)
    else:
        print("Invalid choice!")
        return None

    while True:
        print("\nChoose an operation:")
        print("1. Indexing")
        print("2. Slicing")
        print("3. Go Back")

        op = int(input("Enter your choice: "))

        if op == 1:
            i = int(input("Row index: "))
            j = int(input("Column index: "))
            print("Value:", self.arr[i][j])

        elif op == 2:
            r1, r2 = map(int, input("Enter the row range (start:end): ").split(":"))
            c1, c2 = map(int, input("Enter the column range (start:end): ").split(":"))

            print("\nSliced Array:")
            print(self.arr[r1:r2, c1:c2])

        elif op == 3:
            break

def mathematical_operations(arr):
    print("\nMathematical Operations:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    ch = int(input("Enter your choice: "))

    elements = list(map(int, input("Enter same-size array elements separated by space: ").split()))
    arr2 = np.array(elements).reshape(arr.shape)

    print("\nOriginal Array:\n", arr)
    print("Second Array:\n", arr2)

    if ch == 1:
        print("Result of Addition:\n", arr + arr2)
    elif ch == 2:
        print("Result of Subtraction:\n", arr - arr2)
    elif ch == 3:
        print("Result of Multiplication:\n", arr * arr2)
    elif ch == 4:
        print("Result of Division:\n", arr / arr2)

def combine_split(arr):
    print("\nCombine or Split Arrays:")
    print("1. Combine Arrays")
    print("2. Split Array")
    ch = int(input("Enter your choice: "))

    if ch == 1:
        elements = list(map(int, input("Enter elements of another array separated by space: ").split()))
        arr2 = np.array(elements).reshape(arr.shape)
        combined = np.vstack((arr, arr2))
        print("\nCombined Array (Vertical Stack):\n", combined)

    elif ch == 2:
        parts = int(input("Enter number of splits: "))
        split_arr = np.array_split(arr, parts)
        print("\nSplit Arrays:")
        for s in split_arr:
            print(s)

def search_sort_filter(arr):
    print("\nSearch, Sort, and Filter:")
    print("1. Search a value")
    print("2. Sort the array")
    print("3. Filter values")
    ch = int(input("Enter your choice: "))

    if ch == 1:
        val = int(input("Enter value to search: "))
        print("Found at positions:", np.where(arr == val))

    elif ch == 2:
        print("\nSorted Array (row-wise):")
        print(np.sort(arr, axis=1))

    elif ch == 3:
        val = int(input("Enter filter value (> value): "))
        print("Filtered Values:", arr[arr > val])

def aggregates_statistics(arr):
    print("\nAggregates and Statistics:")
    print("1. Sum")
    print("2. Mean")
    print("3. Median")
    print("4. Standard Deviation")
    print("5. Variance")
    ch = int(input("Enter your choice: "))

    print("\nOriginal Array:\n", arr)

    if ch == 1:
        print("Sum:", np.sum(arr))
    elif ch == 2:
        print("Mean:", np.mean(arr))
    elif ch == 3:
        print("Median of Array:", np.median(arr))
    elif ch == 4:
        print("Standard Deviation:", np.std(arr))
    elif ch == 5:
        print("Variance:", np.var(array))

  # Main Menu            
print("Welcome to the NumPy Analyzer!")
print("=" * 40)

array = None

while True:
    print("\nChoose an option:")
    print("1. Create a NumPy Array")
    print("2. Perform Mathematical Operations")
    print("3. Combine or Split Arrays")
    print("4. Search, Sort, or Filter Arrays")
    print("5. Compute Aggregates and Statistics")
    print("6. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        array = create_array()
        print("\nArray created successfully:\n", array)

    elif choice == 2 and array is not None:
        mathematical_operations(array)

    elif choice == 3 and array is not None:
        combine_split(array)

    elif choice == 4 and array is not None:
        search_sort_filter(array)

    elif choice == 5 and array is not None:
        aggregates_statistics(array)

    elif choice == 6:
        print("\nThank you for using the NumPy Analyzer! Goodbye!")
        break

    else:
        print("⚠️ Please create an array first!")

Welcome to the NumPy Analyzer!

Choose an option:
1. Create a NumPy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  1



Array Creation:
1. 1D Array
2. 2D Array
3. 3D Array


Enter your choice:  2
Enter number of rows:  4
Enter number of columns:  3
Enter 12 elements separated by space:  1 2 3 4 5 6 7 8 9 11 12 13



Array created successfully:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]

Choose an option:
1. Create a NumPy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  2



Mathematical Operations:
1. Addition
2. Subtraction
3. Multiplication
4. Division


Enter your choice:  1
Enter same-size array elements separated by space:  9 8 7 6 5 4 3 2 1 11 12 13



Original Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]
Second Array:
 [[ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]
 [11 12 13]]
Result of Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]
 [22 24 26]]

Choose an option:
1. Create a NumPy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  3



Combine or Split Arrays:
1. Combine Arrays
2. Split Array


Enter your choice:  1
Enter elements of another array separated by space:  8 6 4 5 9 3 1 2 14 15 18 16



Combined Array (Vertical Stack):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [ 8  6  4]
 [ 5  9  3]
 [ 1  2 14]
 [15 18 16]]

Choose an option:
1. Create a NumPy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  4



Search, Sort, and Filter:
1. Search a value
2. Sort the array
3. Filter values


Enter your choice:  2



Sorted Array (row-wise):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]

Choose an option:
1. Create a NumPy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  5



Aggregates and Statistics:
1. Sum
2. Mean
3. Median
4. Standard Deviation
5. Variance


Enter your choice:  1



Original Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]
Sum: 81

Choose an option:
1. Create a NumPy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit


Enter your choice:  6



Thank you for using the NumPy Analyzer! Goodbye!
